# Generated by Django 5.1.5 on 2025-04-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=15)),
                ("position", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=50)),
                ("hours_per_week", models.FloatField()),
                ("hourly_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
