# Generated by Django 5.1.5 on 2025-04-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(max_length=12),
        ),
    ]
